### ISSUE TITLE
카드 기능 테스트가 실패하는 문제

### ISSUE THREAD

**Issue by kyupid** [kyupid/test-dev-process-with-todo-list#1]
커밋: 9e879370b11b31c4a2df333a65f937288b3c11d4

## 코드

```java
package com.example.todolist.service;

import com.example.todolist.domain.Card;
import com.example.todolist.domain.Column;
import com.example.todolist.dto.CardRequestDTO;
import com.example.todolist.exception.ColumnNotFoundException;
import com.example.todolist.repository.CardRepository;
import com.example.todolist.repository.ColumnRepository;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;

import java.util.Optional;

import static org.mockito.Mockito.*;

@SpringBootTest
public class CardServiceTest {

    @MockBean
    private CardRepository cardRepository;

    @MockBean
    private ColumnRepository columnRepository;

    @MockBean
    private Column column;

    @MockBean
    private CardRequestDTO cardRequest;

    @MockBean
    CardService cardService;

    @Test
    @DisplayName("카드 추가 기능 테스트")
    void addCard() {
        Long columnId = 1L;

        when(columnRepository.findById(anyLong())).thenReturn(Optional.of(column));

        cardService.addCard(columnId, cardRequest);

        verify(cardRepository, times(1)).save(any(Card.class));
    }

    @Test
    @DisplayName("컬럼이 없을 시 ColumnNotFoundException 발생 테스트")
    void addCardColumnNotFoundException() {
        Long columnId = 1L;

        when(columnRepository.findById(anyLong())).thenThrow(ColumnNotFoundException.class);

        Assertions.assertThrows(ColumnNotFoundException.class, () -> cardService.addCard(columnId, cardRequest));

        verify(cardRepository, never()).save(any(Card.class));
    }
}
```
### 카드 추가 기능 테스트
> - cardRepository.save()가 호출안됨
> - 인터렉션 자체가 없었다.
```


Wanted but not invoked:
cardRepository bean.save(
    <any com.example.todolist.domain.Card>
);
-> at com.example.todolist.service.CardServiceTest.addCard(CardServiceTest.java:52)
Actually, there were zero interactions with this mock.

Wanted but not invoked:
cardRepository bean.save(
    <any com.example.todolist.domain.Card>
);
-> at com.example.todolist.service.CardServiceTest.addCard(CardServiceTest.java:52)
Actually, there were zero interactions with this mock.

    at com.example.todolist.service.CardServiceTest.addCard(CardServiceTest.java:52)
  ...
  ...
  ...

```
### 컬럼이 없을시 ColumnNotFoundException
> - ColumnNotFoundExcption이 throw안되어졌다.

```
Expected com.example.todolist.exception.ColumnNotFoundException to be thrown, but nothing was thrown.
org.opentest4j.AssertionFailedError: Expected com.example.todolist.exception.ColumnNotFoundException to be thrown, but nothing was thrown.
 ...
 ...
    at com.example.todolist.service.CardServiceTest.addCardColumnNotFoundException(CardServiceTest.java:64)
 ...
 ...


```

**Comment by kyupid** [comment]
## 문제 접근과 해결
```
cardService.addCard(columnId, cardRequest);
```
위 코드에서 cardServce가 `@MockBean`으로 Mocking 되어 있는데,
`addCard()`를 호출할때 사용하는 `CardRepository`와 `ColumnRepository`도 자동 Mocking 되어지는 것인가?
자동 Mocking 안되어지는 거라면 이게 문제일 가능성이 높고 자동 Mocking 되는 것이면 문제가 아니고.

### service를 mocking 해서 테스트하는 것말고 mocked repository 를 바로 호출해보자
```
    @MockBean
    private CardRepository cardRepository;

    @Test
    @DisplayName("의존성 없는 단일 Repository 테스트")
    void testRepository() {
        //given
        Card card = mock(Card.class);
        //when
        cardRepository.save(card);
        //then
        verify(cardRepository, times(1)).save(any(Card.class));
    }
```
![2022-03-09_00-17-43](https://user-images.githubusercontent.com/59721293/157267694-950f9362-0a21-4930-9dab-9c374b274adf.jpg)
이게 의미하는바는 더욱이 `addCard()`를 호출할때 제대로 작동안했다는 것 -> mocked repositories가 아니라 real ones 를 사용했을 확률 업

### (추측) service만 mock 되었으니까 해당 서비스 안에 있는 repositories도 mock 하자

- 대충 mockito mocking service 로 검색
- `@InjectMocks` 발견 -> 이름에서부터 다른 mock 들을 inject한다는 느낌이 뿜뿜
- `@InjectMocks private CardService cardService`로 변경
- 에러메시지가 바뀜
```
java.lang.NullPointerException
	at com.example.todolist.service.CardService.addCard(CardService.java:20)
```
- `when(columnRepository.findById(anyLong())).thenReturn(Optional.of(column));` 에 의해서 해당 라인이 NPE가 나올수가 없는데 나왔다는 이유는 mocked repository가 들어가지 않았다는 것.
- 하지만 `@MockBean`으로 이미 mock 해줌 -> 엥?
- 혹시 몰라 `@Mock`으로 바꾸니 null이 안뜸

> **모든 `@MockBean`어노테이션을 `@Mock`으로 바꿈** -> 모든 테스트 패스


### `@Mock` vs `@MockBean`
#### `@Mock, Mockito.mock()`
- 그냥 Mocked 객체들

#### @MockBean
- Spring Boot에서 제공하는 Mockito 라이브러리를 래핑한 어노테이션
- Mockito mocks들을 Spiring ApplicationContext에 추가해준다
- context에 이미 선언된 bean이라면 mocked one으로 대체한다
- 그게 아니라면 그냥 추가한다
- 즉 테스트시에 context가 필요하다면 이 어노테이션을 사용해야한다
